export const SOCIAL_LOGIN_ACTION = 'SOCIAL_LOGIN_ACTION';

export const ADD_PHONE_NO_ACTION = 'ADD_PHONE_NO_ACTION';

export const OTP_VERIFICATION_ACTION = 'OTP_VERIFICATION_ACTION';

export const RESEND_OTP_ACTION = 'RESEND_OTP_ACTION';

export const SIGN_UP_ACTION = 'SIGN_UP_ACTION';

export const GET_CONFIGURATION_ACTION = 'GET_CONFIGURATION_ACTION';

export const LOGOUT_ACTION = 'LOGOUT_ACTION';

export const GET_PROFILE_ACTION = 'GET_PROFILE_ACTION';

export const EMAIL_VERIFICATION_ACTION = 'EMAIL_VERIFICATION_ACTION';

export const FORGET_PASSWORD_ACTION = 'FORGET_PASSWORD_ACTION';

export const RESET_PASSWORD_ACTION = 'RESET_PASSWORD_ACTION';

export const LOGIN_ACTION = 'LOGIN_ACTION';

export const EDIT_PROFILE_ACTION = 'EDIT_PROFILE_ACTION';
